language: python
python:
- '3.6'
sudo: true
os:
- linux
dist:
# take the latest supported version
- bionic
compiler:
- gcc

# install dependencies

before_install:
# install latest r
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
- sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
- sudo apt-get update
- sudo apt-get install r-base

addons:
  apt:
    update: true
    packages:
    - redis-server
    - libhdf5-serial-dev
    - libatlas-base-dev
    - swig3.0

install:
- mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
- pip install --upgrade .
- pip install --upgrade -r .travis_pip_reqs.txt
- pip install --upgrade pytest
- pip install https://github.com/icb-dcm/petab/archive/develop.zip
- pip install -e git+https://github.com/icb-dcm/amici.git@develop#egg=amici\&subdirectory=python/sdist
- git clone --depth 1 https://github.com/petab-dev/petab_test_suite tmp/petab_test_suite
- pip install -e tmp/petab_test_suite

# run tests

script:
- travis_wait 10 python -m pytest --cov=pyabc test/test_*
- travis_wait 3 xvfb-run -a python -m pytest --cov=pyabc --cov-append test/visualization/test_*
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_wait 15 test/run_notebooks.sh; fi

after_success:
- codecov

# deploy

deploy:
  provider: pypi
  username: yannik.schaelte
  password:
    secure: OrrncJ6ne3gL/KtkvW47Vy2aymDtSVR05fgqhEZWCOR/MCilocjW24UGLsLfrVnhzOkoZCdir+7/ACCYr+NwznA6aqqYlSJ4qGEmFCol5htejQLZVtI5CX+otjsuF/utHyqSIVLNf2cDtXX9TSqUW7TsJh0YHrPtH8gUDr5kzZLNBdn4oCh9xVM4P1/FgWx5hEj9H1X62hOURZxKFs1mK+JxryNjFla/agaEzypHKTYMn+q1biRaQlMl+93JQs85kRQWoxOab6sn1B2CUfRezGs5wjj/zIBHvwPpIsJGniMtBan+xKqkJls4t5gGPss1CyVqWc6Eb8l4pg9kXTFUN30fKEYAmF2WRj1HwyCWumKXUzZ/vOCRtN91RyrtEkc/SOlmg5MvBNiKaaDO45R644LeMav1PaAt1GJxfqb8J9fBcMRbYYwheu7u/dOMUTl4HxuVoq3qtIdgnpdL22+UAaWRmcSKfJCcST8U4wOfTmsP2YcPog4IM7HoW7QfwGLlHR1VHUUGcPf1CDNC74jpSUu2qSDpdGJHVxBRQw48vak9eYA+pPbAellU5BQo6N6BjKM1oDWnc54du/C5bKmC6oNEv2d+LMvrFfmttFuOKxJEuooIHs3fDuvJHRjvEylImjn+L6wu5n0t4HnKP8t9ur85XLupLKTaTp6eVuC8fuA=
  on:
    branch: master
    tags: true

# cache

cache: pip
