language: python
python:
  - "3.6"

sudo: true

# environment

os:
  - linux
dist:
  - trusty  # take the latest supported LTS version

# install dependencies

before_install:
  # install latest r
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install r-base r-base-dev r-base-core r-recommended

# from apt
addons:
  apt:
    update: true
    packages:
    - redis-server

# from pip
install:
  - pip install --upgrade .
  - pip install --upgrade -r .travis_pip_reqs.txt
  - pip install --upgrade pytest

# run tests

script:
  - travis_wait 30 python -m pytest --cov test

after_success:
  - codecov

# cache

cache: pip
